services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./myrealm-export.json:/opt/keycloak/data/import/myrealm-export.json:ro
      - keycloak-data:/opt/keycloak/data
    ports:
      - "8080:8080"
    networks:
      - task-manager-net

  postgres-task-db:
    image: postgres:15
    container_name: postgres-task-db
    environment:
      POSTGRES_USER: ${DB_TASK_USERNAME}
      POSTGRES_PASSWORD: ${DB_TASK_PASSWORD}
      POSTGRES_DB: taskdb
    volumes:
      - pgdata-task:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - task-manager-net

  postgres-file-db:
    image: postgres:15
    container_name: postgres-file-db
    environment:
      POSTGRES_USER: ${DB_FILE_USERNAME}
      POSTGRES_PASSWORD: ${DB_FILE_PASSWORD}
      POSTGRES_DB: filedb
    volumes:
      - pgdata-file:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - task-manager-net

  taskserver:
    image: workfred/task-server:latest
    container_name: taskserver
    depends_on:
      - postgres-task-db
      - keycloak
    environment:
      - KEYCLOAK_URL=http://keycloak:8080/realms
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_TASK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_TASK_CLIENT_SECRET}
      - DB_TASK_USERNAME=${DB_TASK_USERNAME}
      - DB_TASK_PASSWORD=${DB_TASK_PASSWORD}
      - DB_TASK_URL=jdbc:postgresql://postgres-task-db:5432/taskdb
      - DB_TASK_TYPE=postgresql
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_SCOPE=${KEYCLOAK_SCOPE}
    ports:
      - "8085:8085"
    networks:
      - task-manager-net

  fileserver:
    image: workfred/file-server:latest
    container_name: fileserver
    depends_on:
      - postgres-file-db
      - keycloak
    environment:
      - KEYCLOAK_URL=http://keycloak:8080/realms
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_FILE_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_FILE_CLIENT_SECRET}
      - DB_FILE_USERNAME=${DB_FILE_USERNAME}
      - DB_FILE_PASSWORD=${DB_FILE_PASSWORD}
      - DB_FILE_URL=jdbc:postgresql://postgres-file-db:5432/filedb
      - DB_FILE_TYPE=postgresql
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_SCOPE=${KEYCLOAK_SCOPE}
      - TASK_API_URL=http://taskserver:8085/api
    ports:
      - "8083:8083"
    networks:
      - task-manager-net

  gateway:
    image: workfred/gateway:latest
    container_name: gateway
    depends_on:
      - fileserver
      - taskserver
      - keycloak
    environment:
      - KEYCLOAK_URL=http://keycloak:8080/realms
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_GATEWAY_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_GATEWAY_CLIENT_SECRET}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_SCOPE=${KEYCLOAK_SCOPE}
      - TASK_API_URL=http://taskserver:8085/api
      - FILE_API_URL=http://fileserver:8083/api
    ports:
      - "8086:8086"
    networks:
      - task-manager-net

volumes:
  keycloak-data:
  pgdata-task:
  pgdata-file:

networks:
  task-manager-net:
    driver: bridge
